<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SchematicControls.Abstractions</RootNamespace>
    <AssemblyName>SchematicControls.Abstractions</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Circuit\Circuit.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
</Project>
