<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>WaveAudio</AssemblyName>
    <Product>WaveAudio</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
</Project>