<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>LiveSPICEApp</AssemblyName>
    <Product>LiveSPICEApp</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LiveSPICEVst\LiveSPICEVst.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
</Project>