<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AssemblyName>Asio</AssemblyName>
    <Product>Asio</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AsioWrapper.cs" />
  </ItemGroup>
</Project>